
export const GENERATE_CONSTRUCTOR_DATA      ="GENERATE_CONSTRUCTOR_DATA";
export const ADD_CONSTRUCTOR_INGREDIENT     ="ADD_CONSTRUCTOR_INGREDIENT";
export const REMOVE_CONSTRUCTOR_INGREDIENT  ="REMOVE_CONSTRUCTOR_INGREDIENT";
export const CLEAR_CONSTRUCTOR_DATA         ="CLEAR_CONSTRUCTOR_DATA";

export const GET_CONSTRUCTOR_REQUEST = "GET_CONSTRUCTOR_REQUEST"; 
export const GET_CONSTRUCTOR_FAILED  = "GET_CONSTRUCTOR_FAILED";
export const GET_CONSTRUCTOR_SUCCESS = "GET_CONSTRUCTOR_SUCCESS";
